### ISSUE TITLE
Incomplete animator interface?

### ISSUE THREAD

**Issue by cehoffman** [aurelia/animator-velocity#6]
What is the intended use of this animator?

Right now if you try to use this as the only animator in the application you lose out of any templating features that make use of `addClass` or `removeClass` from the [abstract Animator](https://github.com/aurelia/templating/blob/78018c83e3f48a22d86dc6838afaf4d461f3d13c/src/animator.js#L40).

Is this implementation just missing those methods or is there some mixture of animators that should coexist?

**Comment by EisenbergEffect** [comment]
I think it's an oversight. @Aaike Can you respond to this? It looks like you didn't finish this implementation entirely.

**Comment by samlin99** [comment]
Here is the error message if i included animator-velocity. it will validate with show.js

Unhandled promise rejection TypeError: this.animator.addClass is not a function
    at Show.valueChanged (http://localhost:9004/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.3/show.js:21:23)
    at Show.bind (http://localhost:9004/jspm_packages/npm/aurelia-templating-resources@1.0.0-beta.1.0.3/show.js:26:12)
    at Controller.bind (http://localhost:9004/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:2753:24)
    at View.bind (http://localhost:9004/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:845:24)
    at Controller.bind (http://localhost:9004/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:2751:19)
    at View.bind (http://localhost:9004/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:845:24)
    at Controller.bind (http://localhost:9004/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:2751:19)
    at Controller.automate (http://localhost:9004/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:2705:12)
    at addNextView (http://localhost:9004/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.0.4/router-view.js:112:40)
    at h (http://localhost:9004/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773:66)
    at http://localhost:9004/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1778:19
    at MutationObserver.e (http://localhost:9004/jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1958:55)

**Comment by EisenbergEffect** [comment]
Fixed here: 67a8793fcac53ab7d079d619050377f529bc29c5
